### ISSUE TITLE
Create Salesforce & Sage 50 UK Example

### ISSUE THREAD

**Issue by joeharrisonzynksoftware** [zynksoftware/zynk-workflow-examples#16]
**Is your feature request related to a problem? Please describe.**
We are implementing changes to the Auto Mappers area of Zynk Workflow. As part of this, we would like to provide new example integrations.

**Describe the solution you'd like**
We need to create a Magento & Sage 50 UK example workflow that uses the new auto mappers.

* Salesforce Accounts → Sage 50 UK Customers
* Salesforce Opportunities → Sage 50 UK Sales Orders / Invoices
* Sage 50 UK Inventory + Price → Salesforce Product Inventory and Price

The integration wizard (see [GitHub ticket](https://github.com/zynksoftware/zynk-workflow/issues/992)) will contain a boolean option for this sample, to indicate whether or not the integration should create customers.

A similar option will be added to the wizard to indicate whether orders should be created as sales orders or invoices in Sage.

**Additional context**
You can track the progress of the Auto Mapper changes in [the project](https://github.com/orgs/zynksoftware/projects/31).

**Comment by adammccrory** [comment]
I think this is the ticket for the XSLT example

**Comment by joeharrisonzynksoftware** [comment]
Closing this as not planned, as we are going to be using the zynk-workflow-templates repo for this kind of thing moving forward.

**Comment by adammccrory** [comment]
@joeharrisonzynksoftware is this request in that repo as we have a customer wanting this standard workflow example

**Comment by joeharrisonzynksoftware** [comment]
Yes
